name: Unit Tests

on: [pull_request]

jobs:
  run-ci:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 21
        
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Generate Prisma Artifacts
        run: pnpm install && pnpm prisma generate

      - name: Run Tests
        run: pnpm test